/nas/longleaf/home/gabivla/lab/SV_mosquitos/final_scripts/Evolutionary_constrains/nonreference/frequency_dif_distribution/plot_frequency_difference.py:239: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_SNPs_frequency["frequency_diff"] = abs(df_SNPs_frequency[f"frequency_SNP_{country1}"] - df_SNPs_frequency[f"frequency_SNP_{country2}"])

--- Data for Senegal ---

--- Data for Brazil ---

--- Data for Gabon ---

--- Data for USA ---

--- Data for Colombia ---

--- Data for Kenya ---
Traceback (most recent call last):
  File "/nas/longleaf/home/gabivla/miniconda3/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'count'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nas/longleaf/home/gabivla/lab/SV_mosquitos/final_scripts/Evolutionary_constrains/nonreference/frequency_dif_distribution/plot_frequency_difference.py", line 251, in <module>
    plt.plot(diff_counts["frequency_diff"], diff_counts["count"], linestyle="-", color="b", label="TE Frequency Difference")
                                            ~~~~~~~~~~~^^^^^^^^^
  File "/nas/longleaf/home/gabivla/miniconda3/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas/longleaf/home/gabivla/miniconda3/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'count'
